title: 321Niche
description: Helping you find and monetize your niche.

# Base URL of the Site
url: "https://321niche.com"  
# Pagination Settings
paginate: 5
paginate_path: "/blog/page:num"

plugins:
  - jekyll-paginate
  - jekyll-sitemap  # Added the sitemap plugin here

# Default Layout for Posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Collections Settings
collections:
  posts:
    output: true

# Commented out the theme line to use custom layouts
# theme: minima
