# _config.yml

title: 321Niche
description: Discover your future niche and turn your passion into income. 321Niche provides tools, resources, and community support to help you succeed.
baseurl: "" # e.g., "/blog" if hosted in a subdirectory
url: "https://www.321niche.com" # Replace with your actual site URL

theme: null # Set to null if not using a predefined theme

plugins:
  - jekyll-paginate
  - jekyll-sitemap # Optional: For sitemap generation

paginate: 10
paginate_path: "/blog/page:num/"

markdown: kramdown

# Exclude directories from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
