title: 321Niche
description: Helping you find and monetize your niche.

# Pagination Settings
paginate: 5
paginate_path: "/blog/page:num"

plugins:
  - jekyll-paginate

# Default Layout for Posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Commented out the theme line to use custom layouts
# theme: minima
