theme: minima
title: 321Niche
description: Helping you find and monetize your niche.

# Pagination Settings
paginate: 10
paginate_path: "/blog/page:num"

# Default Layout for Posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post" # Can adjust this to "blog" if you have a separate blog layout
