# _config.yml

title: 321Niche
description: Discover your future niche and turn your passion into income. 321Niche provides tools, resources, and community support to help you succeed.
baseurl: "" # e.g., "/blog" if hosted in a subdirectory
url: "https://www.321niche.com" # Replace with your actual site URL

theme: null # Set to null if not using a predefined theme

# Plugins
plugins:
  - jekyll-paginate-v2  # Use this plugin for better pagination
  - jekyll-sitemap      # Optional: For sitemap generation

# Pagination Settings (Updated for jekyll-paginate-v2)
pagination:
  enabled: true
  per_page: 10           # Number of posts per page
  permalink: '/blog/page/:num/'
  title: ' - Page :num'

# Markdown Configuration
markdown: kramdown

# Exclude directories from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
