[build]
  publish = "docs/"  # Assuming your build output is in the "docs" folder

[[redirects]]
  from = "/.netlify/functions/nicheAnalyzer"
  to = "/.netlify/functions/nicheAnalyzer.js" 
  status = 200
  force = true
  methods = ["POST", "OPTIONS"]
