[build]
  publish = "_site"

[functions]
  directory = "netlify/functions" # This line tells Netlify where to find your functions

[[redirects]]
  from = "/nicheAnalyzer"
  to = "/.netlify/functions/nicheAnalyzer"
  status = 200
  force = true
  methods = ["POST", "OPTIONS"]
