[build]
  publish = "_site/"

[functions]
  directory = "netlify/functions" # This line tells Netlify where to find your functions

[[redirects]]
  from = "/.netlify/functions/nicheAnalyzer"
  to = "/.netlify/functions/nicheAnalyzer.js" 
  status = 200
  force = true
  methods = ["POST", "OPTIONS"]
