[build]
  publish = "_site"

[functions]
  directory = "functions" # Updated path to point to the correct functions folder

[[redirects]]
  from = "/.netlify/functions/nicheAnalyzer"
  to = "/functions/nicheAnalyzer.js"  # Adjusted to match the root-level location of the function file
  status = 200
  force = true
  methods = ["POST", "OPTIONS"]
